version: '3.5'
services:
  webservice:
    restart: always
    privileged: true
    container_name: webapi
    ports:      
      - "8080:8080"
    networks:
      - microservice
    build:
      context: ./webapi
      dockerfile: Dockerfile
    environment:
      - AMQP_URL=amqp://guest:guest@mqtt:5672
    depends_on: 
      - mqtt

  client:
    restart: always
    privileged: true  
    container_name: client
    ports:      
      - "5000:80"
    networks:
      - microservice
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on: 
      - webservice

  mqtt:
    image: "rabbitmq:alpine"  
    container_name: mqtt
    networks:
      - microservice
    ports:
      - 5672:5672
      - 15672:15672
  
networks:
  microservice: