version: '3.5'
services:
  webapi:
    restart: always
    privileged: true
    container_name: webapi
    ports:      
      - "8080:8080"
    networks:
      - microservice
    build:
      context: ./webapi
      dockerfile: Dockerfile

  client:
    restart: always
    privileged: true
    container_name: client
    ports:      
      - "5000:80"
    networks:
      - microservice
    build:
      context: ./client
      dockerfile: Dockerfile
  
networks:
  microservice: