version: '3.5'
services:
  api-gateway:
    restart: always
    privileged: true
    container_name: api-gateway
    ports:
      - "5001:80"
    networks:
      - microservice
    build:
      context: ./api-gateway
      dockerfile: Dockerfile

  roundtrip-service:
    restart: always
    privileged: true
    container_name: roundtrip-service
    networks:
      - microservice
    build:
      context: ./roundtrip-service
      dockerfile: Dockerfile
    environment:
      - AMQP_URL=amqp://guest:guest@mqtt:5672
      - BATCH_SIZE=500
    depends_on: 
      - mqtt
  
  batch-service:
    container_name: batch-service
    restart: always
    privileged: true
    networks:
      - microservice
    build:
      context: ./batch-service
      dockerfile: Dockerfile
    environment:
        - ASPNETCORE_URLS=http://+:8040
        - AMQP_URL=amqp://guest:guest@mqtt:5672
        - REDIS_URL=redis:6379
    depends_on:
        - mqtt
        - redis
  
  websocket-service:
    restart: always
    privileged: true
    container_name: websocket-service
    networks:
      - microservice
    environment: 
      - AMQP_URL=amqp://guest:guest@mqtt:5672
    build:
      context: ./websocket-service
      dockerfile: Dockerfile
    depends_on: 
      - mqtt
  
  client:
    restart: always
    privileged: true  
    container_name: client
    ports:      
      - "5000:80"
    networks:
      - microservice
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on: 
      - roundtrip-service
      - batch-service
      - websocket-service
  
  redis-service:
    restart: always
    privileged: true
    container_name: redis-service
    networks: 
      - microservice
    build:
      context: ./redis-service
      dockerfile: Dockerfile
    environment: 
      - AMQP_URL=amqp://guest:guest@mqtt:5672
      - REDIS_URL=redis://redis:6379
    depends_on: 
      - mqtt 
      - redis

  mqtt:
    image: "rabbitmq:management-alpine"  
    container_name: mqtt
    restart: always
    privileged: true
    networks:
      - microservice

  redis:
    image: "redis:6-alpine"
    container_name: redis
    restart: always
    privileged: true
    command: redis-server --appendonly yes
    volumes:
      - ~/redis-data:/data
    networks: 
      - microservice
  
networks:
  microservice: